print("Trig Derivative Identities")
print("------------------------------")
print("dx(sinx) = cosxprint")
print("dx(cosx) = -sinx")
print("dx(tanx) = sec^2x")
print("dx(cscx) = -cotxcscx")
print("dx(secx) = tanxsecx")
print("dx(cotx) = -csc^2x")
print("------------------------------")

print("Trig Integral Identities")
print("------------------------------")
print("int(sinx)dx = -cosx + c")
print("int(cosx)dx = sinx + c")
print("int(csc^2x)dx = -cotx + c")
print("int(sec^2x)dx = tanx + c")
print("int(cscxcotx)dx = -cscx + c")
print("int(secxtanx)dx = secx + c")
print("------------------------------")

print("Natural Log Rules")
print("------------------------------")
print("ln(a•b) = lna + lnb")
print("ln(a/b) = lna - lnb")
print("ln(a^b) = blna")
print("(lnx)' = 1/x")
print("(lnu)' = (1/u)•u'")
print("------------------------------")

print("Inverse Function Rules")
print("------------------------------")
print("f(x) maps an x input to a y output")
print("f^-1(x) maps a y input to an x output")
print("replace f(x) with y, swap x and y, solve for inverse function")
print("one-to-one functions pass the horizonal line test")
print("a horizontal line cannot touch 2 points at once on the HLT")
print("even functions cannot be one-to-one")
print("------------------------------")

print("Fundamental Theorem of Calculus")
print("------------------------------")
print("x=b/int/a means upper bound b, lower bound a")
print("let f(x) be continuous on [a,b]. Then, for a≤x≤b")
print("a) d/dx x/int/a(f(t))dt = f(x)")
print("b) b/int/a (f(x))dx = F(b)-F(a) where F'(x)=f(x)")
print("------------------------------")